const ToursData = {
  destinations: [
    {
      id: 1,
      title: "SANTORINI",
      description: 'Its wild volcanic landscape, rugged cliffs, wild nature, and beautiful shores, combined with its rich history and traditions, make the island the gem of Greece.',
      image: 'https://wallpapercave.com/wp/7hBea5D.jpg',
      tour_plan: {

        line_1: `Arrive in Fira, the capital of Santorini, and explore the local shops and cafes.`,
        line_2: `Visit the Archaeological Museum of Thera to learn about the island's ancient history.`,
        line_3: `Enjoy the breathtaking sunset at Oia, the most famous spot on the island.`,
        line_4: `Take a boat tour to the volcanic islands of Nea Kameni and Palea Kameni.`,
        line_5: ` Relax on the black sand beaches of Kamari or Perissa.`,
        line_6: ` Visit the Akrotiri archaeological site, a Minoan Bronze Age settlement.`,
        line_7: ` Explore the village of Pyrgos, known for its traditional architecture and panoramic views.`,
        line_8: `Wine tasting at a local winery, such as Santo Wines, to enjoy the unique flavors of Santorini's wines.`,
        line_9: ` Hike from Fira to Oia along the caldera edge for stunning views.`,
        line_10: ` Experience the vibrant nightlife in Fira or Imerovigli.`,
      },
      price: 272000,
      qnty: 0,

    },
    {
      id: 2,
      title: "PERU",
      description: 'It consists of a coastal plain in the west, high rugged mountains in its center, a lowland jungle in the east that leads into the Amazon River basin.',
      image: 'https://i.pinimg.com/originals/12/dc/e0/12dce0fe1da430628d60aea799427748.jpg',
      tour_plan: {
        line_1: ` Arrive in Lima and explore the historic center, including Plaza Mayor and the Cathedral.`,
        line_2: `Visit the Larco Museum to see an extensive collection of pre-Columbian art.`,
        line_3: `Fly to Cusco and acclimate to the altitude by exploring the city's Plaza de Armas and nearby markets.`,
        line_4: `Take a day trip to the Sacred Valley, visiting Pisac, Ollantaytambo, and the local markets.`,
        line_5: ` Begin the Inca Trail trek to Machu Picchu, passing through beautiful landscapes and ancient ruins.`,
        line_6: `Arrive at Machu Picchu and explore the ancient Incan citadel, one of the New Seven Wonders of the World.`,
        line_7: `Visit the Maras Salt Mines and the Moray archaeological site.`,
        line_8: `Take a scenic train ride to Lake Titicaca, the highest navigable lake in the world.`,
        line_9: `Explore the Uros Floating Islands and Taquile Island on Lake Titicaca.`,
        line_10: `Return to Lima for a final night, enjoying the city's renowned culinary scene.`,
      },
      price: 338000,
      qnty: 0,

    },
    {
      id: 3,
      title: "JAPAN",
      description: 'Japan is a country famous for cherry blossoms, castles, samurai swords, and much more. The island nation has a vibrant history. It is packed with Shrines and religious sites.',
      image: 'https://wallpapercave.com/wp/ma2ov2Z.jpg',
      tour_plan: {
        line_1: `Visit Asakusa to see Senso-ji Temple and Nakamise Shopping Street.`,
        line_2: `Explore the Tokyo Skytree or Ueno Park and its museums.`,
        line_3: ` Experience nightlife in Shibuya or enjoy a traditional izakaya dinner.`,
        line_4: `Explore Hakone Open-Air Museum, take a boat cruise on Lake Ashi, and ride the Hakone Ropeway for views of Mt. Fuji.`,
        line_5: ` Visit Fushimi Inari Shrine with its iconic torii gates.`,
        line_5: `Visit Kinkaku-ji (Golden Pavilion) and Ryoan-ji Temple.`,
        line_6: ` Explore Arashiyama Bamboo Grove and Togetsukyo Bridge.`,
        line_7: `Visit Todai-ji Temple with its Great Buddha, Nara Park (deer park),and Kasuga Taisha Shrine.`,
        line_8: `Visit Osaka Castle and the Floating Garden Observatory.`,
        line_9: `Explore Dotonbori for street food and shopping.`,
      },
      price: 212000,
      qnty: 0,

    },
    {
      id: 4,
      title: "BHUTAN",
      description: 'Bhutan is the only country that is carbon negative.',
      image: 'https://live.staticflickr.com/4488/37950637316_dda45d08f7_k.jpg',
      tour_plan: {
        line_1: `Arrive in Paro and visit the National Museum of Bhutan to learn about the country’s history and culture.`,
        line_2: `Hike to the iconic Tiger’s Nest Monastery (Paro Taktsang), perched on a cliff 3,000 meters above sea level.`,
        line_3: `Travel to Thimphu, the capital city, and explore landmarks such as the Tashichho Dzong and the Buddha Dordenma statue.`,
        line_4: `Visit the National Memorial Chorten, a stupa built in memory of the third king of Bhutan.`,
        line_5: `Explore the Folk Heritage Museum to experience traditional Bhutanese rural life.`,
        line_6: `Drive to Punakha and visit the stunning Punakha Dzong, the "Palace of Great Happiness.`,
        line_7: `Hike to the Chimi Lhakhang, also known as the "Fertility Temple," dedicated to Lama Drukpa Kunley.`,
        line_8: `Explore the scenic Phobjikha Valley, home to the endangered black-necked cranes.`,
        line_9: `Visit Gangtey Monastery, a significant religious site with breathtaking views of the valley.`,
        line_10: `Return to Paro for a final day of shopping for local crafts and souvenirs before departure.`,
      },

      price: 156000,
      qnty: 0,

    },
    {
      id: 5,
      title: "KASHMIR",
      description: 'Jammu and Kashmir is well-known for its attractive glory, snow-covered mountains, abundant flora and fauna, elegant memorials, friendly people, and local craftwork.',
      image: 'https://in.musafir.com/uploads/Kashmir_a_Land_of_Unimaginable_Beauty_4_01166904af.webp',
      tour_plan: {
        line_1: `Arrive in Srinagar and take a Shikara ride on Dal Lake, enjoying the views of the houseboats and floating gardens.`,
        line_2: `Visit the Mughal Gardens, including Shalimar Bagh, Nishat Bagh, and Chashme Shahi, known for their stunning architecture and views.`,
        line_3: `Explore the ancient Shankaracharya Temple perched on a hilltop, offering panoramic views of Srinagar.`,
        line_4: `Take a day trip to Gulmarg, a popular ski resort in winter, and enjoy a Gondola ride to Apharwat Peak for spectacular views.`,
        line_5: `Visit Pahalgam, known as the "Valley of Shepherds," for its lush meadows, pine forests, and the starting point for the Amarnath Yatra.`,
        line_6: `Enjoy a pony ride or trek to Betaab Valley, famous for its picturesque setting and Bollywood film shoots.`,
        line_7: `Visit Aru Valley, known for its scenic beauty and opportunities for trekking and camping.`,
        line_8: `Explore Sonamarg, the "Meadow of Gold," surrounded by glaciers and alpine flowers, perfect for nature walks and photography.`,
        line_9: `Take a leisurely walk through the old city of Srinagar, visiting Jamia Masjid and the bustling local markets.`,
        line_10: `End your trip with a visit to the Hazratbal Shrine, a significant Muslim shrine located on the northern shores of Dal Lake.`,
      },
      price: 75000,
      qnty: 0,
    },
    {
      id: 6,
      title: "SWITZERLAND",
      description: 'The abundance of mountains, the country\'s landscape is actually pretty diverse. In the northern part of the Alps, like the Bernese Oberland, you\'ll find that the scenery is very green and vibrant.',
      image: 'https://study-eu.s3.eu-west-1.amazonaws.com/uploads/image/path/121/wide_fullhd_switzerland-mountains.jpg',
      tour_plan: {
        line_1: `Arrive in Zurich and explore the Old Town (Altstadt) with its historic architecture, boutiques, and cafes.`,
        line_2: `Visit the Bahnhofstrasse, one of the world’s most exclusive shopping streets, and enjoy a stroll along Lake Zurich.`,
        line_3: `Take a day trip to Rhine Falls, the largest waterfall in Europe, and enjoy boat trips to the falls.`,
        line_4: `Travel to Lucerne and explore the Chapel Bridge (Kapellbrücke) and the Lion Monument.`,
        line_5: `Take a scenic cruise on Lake Lucerne, surrounded by snow-capped mountains and charming villages.`,
        line_6: `Ride the world’s steepest cogwheel railway up to Mount Pilatus for breathtaking views of the Alps.`,
        line_7: `Head to Interlaken, the adventure capital of Switzerland, and try paragliding, skydiving, or a boat ride on Lake Thun.`,
        line_8: `Visit Jungfraujoch, known as the "Top of Europe," via a scenic train ride, and experience the Ice Palace and panoramic views.`,
        line_9: `Explore Zermatt, a car-free mountain village at the base of the Matterhorn, and take the Gornergrat Railway for stunning views of the peak.`,
        line_10: `End your trip in Geneva, visiting the United Nations Headquarters, the Jet d’Eau fountain, and the Flower Clock.`,
      },
      price: 250000,
      qnty: 0,
    },
    {
      id: 7,
      title: "SIKKIM",
      description: 'Sikkim is notable for its biodiversity, including alpine and subtropical climates, as well as being a host to Kanchenjunga, the highest peak in India and third highest on Earth.',
      image: 'https://wallpapercave.com/wp/wp6191565.jpg',
      tour_plan: {

        line_1: `Arrive in Gangtok, the capital of Sikkim, and visit the MG Marg for shopping and local cuisine.`,
        line_2: `Visit the Enchey Monastery, a 200-year-old monastery offering peaceful surroundings and scenic views.`,
        line_3: `Take a day trip to Tsomgo Lake, a glacial lake at an altitude of 3,753 meters, and visit the nearby Baba Harbhajan Singh Temple.`,
        line_4: `Explore Nathula Pass, the Indo-China border, and enjoy the breathtaking views of the Himalayas.`,
        line_5: `Travel to Lachen, a picturesque mountain village, and visit the Gurudongmar Lake, one of the highest lakes in the world.`,
        line_6: `Head to Lachung, a quaint town known for its beautiful apple orchards and scenic valleys.`,
        line_7: `Visit Yumthang Valley, known as the "Valley of Flowers," and enjoy the hot springs surrounded by snow-covered mountains.`,
        line_8: `Take a detour to Zero Point, the last outpost of civilization, where you can experience snow year-round.`,
        line_9: `Explore the ancient Pemayangtse Monastery in Pelling, offering panoramic views of the Kanchenjunga range.`,
        line_10: `Visit the Rabdentse Ruins, the remains of the former royal palace of Sikkim, surrounded by lush greenery and history.`,
      },
      price: 35000,
      qnty: 0,
    },
    {
      id: 8,
      title: "KERALA",
      description: 'Kerala, often referred to as God\'s Own Country, is a land of captivating beauty and rich cultural heritage. This lush state is renowned for its serene backwaters, pristine beaches, and vibrant hill stations.',
      image: 'https://wallpapercave.com/wp/wp2894162.jpg',
      tour_plan: {

        line_1: `Arrive in Kochi and explore Fort Kochi, known for its colonial architecture, Chinese fishing nets, and vibrant art scene.`,
        line_2: `Visit the Mattancherry Palace and the Paradesi Synagogue in the historic Jew Town.`,
        line_3: `Travel to Munnar, a hill station known for its tea plantations, and visit the Eravikulam National Park to see the endangered Nilgiri Tahr.`,
        line_4: `Explore the Tea Museum in Munnar and take a guided tour of a tea plantation.`,
        line_5: `Head to Thekkady and enjoy a boat safari on Periyar Lake in the Periyar Wildlife Sanctuary, known for its elephants and diverse wildlife.`,
        line_6: `Visit the spice plantations in Thekkady to learn about the spices that Kerala is famous for.`,
        line_7: `Travel to Kumarakom and enjoy a houseboat cruise on the backwaters, experiencing the tranquil beauty of Kerala’s waterways.`,
        line_8: `Explore the Kumarakom Bird Sanctuary, home to a variety of migratory birds.`,
        line_9: `Visit Alleppey, known as the "Venice of the East," and explore its canals, beaches, and backwaters.`,
        line_10: `End your trip in Kovalam, relaxing on its famous beaches, and visit the nearby Padmanabhaswamy Temple in Thiruvananthapuram.`,
      },
      price: 50000,
      qnty: 0,
    },
    {
      id: 9,
      title: "RAJASTHAN",
      description: 'Rajasthan is renowned for its stunning architecture, rich history, colorful culture, and natural beauty. Some of the popular tourist attractions are: The majestic Amber Fort, The iconic Hawa Mahal.',
      image: 'https://wallpapercave.com/wp/wp4021369.jpg',
      tour_plan:{ 
        line_1:`Arrive in Jaipur, the "Pink City," and visit the City Palace, Jantar Mantar, and Hawa Mahal.`,
        line_2: `Explore the majestic Amber Fort, located on a hilltop, and take an elephant ride to the fort.`,
        line_3:`Visit Nahargarh Fort and Jaigarh Fort, offering panoramic views of Jaipur.`,
        line_4:`Travel to Jodhpur, the "Blue City," and visit the Mehrangarh Fort, one of the largest forts in India.`,
        line_5:`Explore the Umaid Bhawan Palace, a luxurious heritage hotel and museum, showcasing royal artifacts.`,
        line_6: `Head to Udaipur, the "City of Lakes," and visit the City Palace, Lake Pichola, and Jag Mandir.`,
        line_7:`Enjoy a boat ride on Lake Pichola, offering stunning views of the Lake Palace and surrounding hills.`,
        line_8:`Visit the Saheliyon Ki Bari, a historic garden in Udaipur known for its fountains and marble pavilions.`,
        line_9: `Travel to Jaisalmer, the "Golden City," and explore the Jaisalmer Fort, a UNESCO World Heritage Site.`,
        line_10:`Experience a camel safari in the Thar Desert, and spend a night in a desert camp under the stars.`,
      },
      price: 45000,
      qnty: 0,
    }
  ]
};
export default ToursData;

